# Notebook 1: Introduction to NumPy

**Sprint 3: NumPy & Pandas for AI/ML Engineers**

---

## 1. What is NumPy?

NumPy (Numerical Python) is a Python library for working with **fast, fixed-type, multi-dimensional arrays** and for doing math on them. Its main object is the **ndarray** (n-dimensional array).

**Analogy:** A Python list is like a bag where every item can be a different thing (a number, a name, a list). A NumPy array is like an egg tray: every slot holds the same kind of thing, in a neat grid, so you can handle the whole tray at once.

## 2. Why NumPy?

| | Python list | NumPy array |
|---|---|---|
| Data type | Mixed types allowed | One fixed type (homogeneous) |
| Speed | Slow (Python loop needed) | Fast (vectorized, runs in C) |
| Memory | Stores pointers to objects | Stores raw values side by side |
| Math on whole data | `[1,2]*2` repeats the list | `arr*2` multiplies every element |
| Dimensions | Nested lists, awkward | Built-in N-dimensional support |

**Real-world example:** An image is a grid of pixel numbers. Making it 20% brighter means multiplying every pixel by 1.2. With NumPy this is one line.

**Business example:** A store has 1 million bills. Adding 18% GST to every bill is one NumPy expression instead of a million-step loop.

**AI/ML example:** Every ML library (Pandas, scikit-learn, TensorFlow, PyTorch) is built on NumPy-like arrays. A dataset is a 2D array (rows = samples, columns = features), an image is a 3D array (height, width, channels), and model weights are arrays.

In [2]:
import numpy as np
import sys
import time

print("NumPy version:", np.__version__)

n = 1_000_000
py_list = list(range(n))
np_arr = np.arange(n)

# Speed: multiply every element by 2
start = time.perf_counter()
result_list = [x * 2 for x in py_list]
list_time = time.perf_counter() - start

start = time.perf_counter()
result_arr = np_arr * 2
arr_time = time.perf_counter() - start

print(f"List loop  : {list_time:.4f} seconds")
print(f"NumPy array: {arr_time:.4f} seconds")
print(f"NumPy is about {list_time / arr_time:.0f}x faster")

# Memory
list_bytes = sys.getsizeof(py_list) + sum(sys.getsizeof(x) for x in py_list)
print("\nList memory (approx):", list_bytes // 1024, "KB")
print("NumPy memory        :", np_arr.nbytes // 1024, "KB")

NumPy version: 2.4.6
List loop  : 0.0461 seconds
NumPy array: 0.0016 seconds
NumPy is about 28x faster

List memory (approx): 35156 KB
NumPy memory        : 7812 KB


**Output Explanation:** The same job (double 1 million numbers) is done with a Python loop and with one NumPy expression. We also compare memory.

**What to expect:** NumPy is usually 20 to 100 times faster, and uses several times less memory, because it stores plain numbers in one block, while a list stores a separate Python object for each number. (Exact numbers differ on every machine.)

**Where used in AI/ML:** Training on millions of rows is only practical because operations run on whole arrays at once.

## 3. NumPy Array (ndarray) and Creating Arrays

An **ndarray** is a grid of values of the **same data type**, indexed by a tuple of integers.

| Function | What it creates |
|---|---|
| `np.array(list)` | Array from a Python list |
| `np.zeros(shape)` | All zeros |
| `np.ones(shape)` | All ones |
| `np.full(shape, value)` | All the same value |
| `np.arange(start, stop, step)` | Range of numbers (stop is excluded) |
| `np.linspace(start, stop, num)` | `num` evenly spaced numbers (stop is included) |
| `np.eye(n)` | Identity matrix |
| `np.empty(shape)` | Uninitialized (random leftover values, fast) |

**Business example:** `np.zeros((12, 5))` can be an empty table for 12 months x 5 products, which we fill later.

**AI/ML example:** Weights of a neural network layer start as arrays of small random numbers or zeros. `np.eye` is used in linear algebra (identity matrix).

In [3]:
a = np.array([10, 20, 30, 40])
print("array   :", a)
print("zeros   :", np.zeros((2, 3)))
print("ones    :", np.ones((2, 2)))
print("full    :", np.full((2, 2), 7))
print("arange  :", np.arange(0, 10, 2))
print("linspace:", np.linspace(0, 1, 5))
print("eye     :\n", np.eye(3))

# 2D array from a nested list
m = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D array:\n", m)

array   : [10 20 30 40]
zeros   : [[0. 0. 0.]
 [0. 0. 0.]]
ones    : [[1. 1.]
 [1. 1.]]
full    : [[7 7]
 [7 7]]
arange  : [0 2 4 6 8]
linspace: [0.   0.25 0.5  0.75 1.  ]
eye     :
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

2D array:
 [[1 2 3]
 [4 5 6]]


**Output Explanation:**
- `arange(0, 10, 2)` gives 0, 2, 4, 6, 8 (10 is **not** included).
- `linspace(0, 1, 5)` gives 0, 0.25, 0.5, 0.75, 1 (1 **is** included).
- `arange` works with a **step size**, `linspace` works with the **number of points**.
- A nested list becomes a 2D array (rows and columns).

## 4. Dimensions, Shape, Size and Data Types

| Attribute | Meaning | Example for a 2 x 3 array |
|---|---|---|
| `ndim` | Number of dimensions (axes) | 2 |
| `shape` | Size along each axis (rows, columns) | (2, 3) |
| `size` | Total number of elements | 6 |
| `dtype` | Data type of the elements | int64 |
| `itemsize` | Bytes per element | 8 |
| `nbytes` | Total bytes | 48 |

**Common dtypes:** `int8/16/32/64`, `float32/float64`, `bool`, `str_`. Smaller types use less memory. `float32` is the usual choice for deep learning.

**Dimensions in AI/ML:**
- 1D: a single row of features, or a list of labels
- 2D: a dataset (samples x features)
- 3D: a batch of text sequences, or one colour image (height x width x 3)
- 4D: a batch of colour images (batch x height x width x 3)

**Type casting** is done with `astype()`. Mixing types makes NumPy **upcast** (`int + float` becomes float).

In [4]:
m = np.array([[1, 2, 3], [4, 5, 6]])

print("ndim    :", m.ndim)
print("shape   :", m.shape)
print("size    :", m.size)
print("dtype   :", m.dtype)
print("itemsize:", m.itemsize, "bytes")
print("nbytes  :", m.nbytes, "bytes")

# Data types
f = np.array([1.5, 2.5, 3.5])
print("\nfloat array dtype:", f.dtype)

mixed = np.array([1, 2.5, 3])           # int + float -> float
print("mixed dtype      :", mixed.dtype, mixed)

text = np.array([1, "a", 3])            # everything becomes text
print("with a string    :", text.dtype, text)

small = np.array([1, 2, 3], dtype=np.int8)
print("int8 nbytes      :", small.nbytes, "| int64 nbytes:", np.array([1, 2, 3]).nbytes)

# Type casting
prices = np.array([10.7, 20.2, 30.9])
print("\nastype(int):", prices.astype(int), "(decimal part is cut, not rounded)")

# 3D example: one tiny RGB image 4 x 4 x 3
image = np.zeros((4, 4, 3), dtype=np.uint8)
print("\nImage shape:", image.shape, "| ndim:", image.ndim)

ndim    : 2
shape   : (2, 3)
size    : 6
dtype   : int64
itemsize: 8 bytes
nbytes  : 48 bytes

float array dtype: float64
mixed dtype      : float64 [1.  2.5 3. ]
with a string    : <U21 ['1' 'a' '3']
int8 nbytes      : 3 | int64 nbytes: 24

astype(int): [10 20 30] (decimal part is cut, not rounded)

Image shape: (4, 4, 3) | ndim: 3


**Output Explanation:**
- `shape (2, 3)` means 2 rows and 3 columns, `size` is 2 x 3 = 6, and `nbytes` is 6 x 8 = 48 for int64.
- Mixing int and float gives a float array. Putting one string in makes the **whole array text**, which is why arrays should be kept numeric for math.
- `int8` uses 1 byte per element instead of 8.
- `astype(int)` **truncates** (10.7 becomes 10), it does not round.
- The image is a 3D array: height 4, width 4, 3 colour channels.

## 5. Indexing

Indexing means picking **one or more elements** by position. Positions start at **0**, and negative positions count from the end (-1 is the last).

| Type | Syntax | Meaning |
|---|---|---|
| 1D | `a[2]` | Third element |
| 2D | `m[1, 2]` | Row 1, column 2 |
| Negative | `a[-1]` | Last element |
| Fancy | `a[[0, 3]]` | Elements at positions 0 and 3 |
| Boolean | `a[a > 25]` | All elements where the condition is True |

**Business example:** `sales[sales > 50000]` picks only the days with sales above 50,000.

**AI/ML example:** Boolean indexing is used for filtering rows (remove invalid values) and for selecting samples of one class.

In [5]:
a = np.array([10, 20, 30, 40, 50])
m = np.arange(1, 13).reshape(3, 4)
print("Matrix:\n", m)

print("\na[0]       :", a[0])
print("a[-1]      :", a[-1])
print("m[1, 2]    :", m[1, 2])
print("m[2, -1]   :", m[2, -1])
print("fancy a[[0, 3]]:", a[[0, 3]])

mask = a > 25
print("\nmask       :", mask)
print("a[a > 25]  :", a[mask])
print("m[m % 2 == 0]:", m[m % 2 == 0])

Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

a[0]       : 10
a[-1]      : 50
m[1, 2]    : 7
m[2, -1]   : 12
fancy a[[0, 3]]: [10 40]

mask       : [False False  True  True  True]
a[a > 25]  : [30 40 50]
m[m % 2 == 0]: [ 2  4  6  8 10 12]


a = np.array([10, 20, 30, 40, 50])
m = np.arange(1, 13).reshape(3, 4)
print("Matrix:\n", m)

print("\na[0]       :", a[0])
print("a[-1]      :", a[-1])
print("m[1, 2]    :", m[1, 2])
print("m[2, -1]   :", m[2, -1])
print("fancy a[[0, 3]]:", a[[0, 3]])

mask = a > 25
print("\nmask       :", mask)
print("a[a > 25]  :", a[mask])
print("m[m % 2 == 0]:", m[m % 2 == 0])

**Output Explanation:**
- `m[1, 2]` is row 1, column 2, which is **7** (rows and columns start at 0).
- `m[2, -1]` is the last element of the last row, which is **12**.
- `a > 25` creates a **True/False mask**. Putting the mask inside `[]` keeps only the True positions.
- Remember `m[1][2]` also works, but `m[1, 2]` is faster and is the NumPy way.

## 6. Slicing

Slicing picks a **range** of elements with `start:stop:step`. The stop position is **not included**.

| Syntax | Meaning |
|---|---|
| `a[1:4]` | Positions 1, 2, 3 |
| `a[:3]` | First three |
| `a[2:]` | From position 2 to the end |
| `a[::2]` | Every second element |
| `a[::-1]` | Reversed |
| `m[0:2, 1:3]` | Rows 0 to 1 and columns 1 to 2 |
| `m[:, 0]` | All rows, first column |
| `m[1, :]` | Second row, all columns |

**Business example:** From a 12-month x 5-product sales table, `sales[:, 2]` gives the whole year's sales of product 3, and `sales[0:3, :]` gives the first quarter.

**AI/ML example:** `X = data[:, :-1]` (all columns except the last are features) and `y = data[:, -1]` (the last column is the target). This is the most common slicing in ML.

**Important:** Basic slicing returns a **view**, not a copy (see Copy vs View).

In [7]:
a = np.arange(10, 110, 10)       # 10, 20, ..., 100
m = np.arange(1, 13).reshape(3, 4)

print("a          :", a)
print("a[1:4]     :", a[1:4])
print("a[:3]      :", a[:3])
print("a[::2]     :", a[::2])
print("a[::-1]    :", a[::-1])

print("\nm:\n", m)
print("m[0:2, 1:3]:\n", m[0:2, 1:3])
print("m[:, 0]    :", m[:, 0])
print("m[1, :]    :", m[1, :])

# ML style: split features and target
data = np.array([[5.1, 3.5, 0], [4.9, 3.0, 0], [6.2, 3.4, 1]])
X = data[:, :-1]
y = data[:, -1]
print("\nX (features):\n", X)
print("y (target)  :", y)

a          : [ 10  20  30  40  50  60  70  80  90 100]
a[1:4]     : [20 30 40]
a[:3]      : [10 20 30]
a[::2]     : [10 30 50 70 90]
a[::-1]    : [100  90  80  70  60  50  40  30  20  10]

m:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
m[0:2, 1:3]:
 [[2 3]
 [6 7]]
m[:, 0]    : [1 5 9]
m[1, :]    : [5 6 7 8]

X (features):
 [[5.1 3.5]
 [4.9 3. ]
 [6.2 3.4]]
y (target)  : [0. 0. 1.]


**Output Explanation:**
- `a[1:4]` gives 20, 30, 40 (position 4 is excluded).
- `a[::-1]` reverses the array.
- `m[0:2, 1:3]` picks rows 0 and 1 and columns 1 and 2, so the result is `[[2, 3], [6, 7]]`.
- `data[:, :-1]` takes all rows and all columns except the last, so it gives the feature matrix `X`. `data[:, -1]` gives the target `y`.

## 7. Reshaping and Flatten

**Reshape** changes the shape of an array **without changing its data**. The total number of elements must stay the same. We can use **-1** for one dimension and NumPy calculates it automatically.

| Method | What it does |
|---|---|
| `a.reshape(3, 4)` | 12 elements into 3 rows x 4 columns |
| `a.reshape(-1, 2)` | Any number of rows, 2 columns |
| `a.flatten()` | 1D **copy** |
| `a.ravel()` | 1D, returns a **view** when possible (faster, no copy) |
| `a.T` | Transpose (swap rows and columns) |
| `a[:, np.newaxis]` | Add a new axis (1D to a column) |

**Real-world example:** A 28 x 28 grayscale image can be flattened into a row of 784 numbers so that a basic ML model can use it as 784 features.

**AI/ML example:** Models expect a fixed shape. `X.reshape(-1, 1)` turns a 1D feature into a column, which scikit-learn needs for a single feature. Images are reshaped from `(batch, 28, 28)` to `(batch, 784)`.

In [8]:
a = np.arange(1, 13)
print("Original:", a, "| shape:", a.shape)

print("\nreshape(3, 4):\n", a.reshape(3, 4))
print("reshape(2, 2, 3) shape:", a.reshape(2, 2, 3).shape)
print("reshape(-1, 6) shape  :", a.reshape(-1, 6).shape)

m = a.reshape(3, 4)
print("\nTranspose shape:", m.T.shape)
print("flatten:", m.flatten())
print("ravel  :", m.ravel())

# 1D feature to a column (needed by scikit-learn)
hours = np.array([2, 4, 6, 8])
print("\nBefore:", hours.shape, "| After reshape(-1, 1):", hours.reshape(-1, 1).shape)

# Wrong reshape
try:
    a.reshape(5, 3)
except ValueError as e:
    print("\nError:", e)

# 28 x 28 image to 784 features
img = np.random.rand(28, 28)
print("Image flattened:", img.flatten().shape)

Original: [ 1  2  3  4  5  6  7  8  9 10 11 12] | shape: (12,)

reshape(3, 4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
reshape(2, 2, 3) shape: (2, 2, 3)
reshape(-1, 6) shape  : (2, 6)

Transpose shape: (4, 3)
flatten: [ 1  2  3  4  5  6  7  8  9 10 11 12]
ravel  : [ 1  2  3  4  5  6  7  8  9 10 11 12]

Before: (4,) | After reshape(-1, 1): (4, 1)

Error: cannot reshape array of size 12 into shape (5,3)
Image flattened: (784,)


**Output Explanation:**
- 12 elements fit into (3, 4), (2, 2, 3) and (-1, 6) because 3 x 4 = 12, 2 x 2 x 3 = 12 and 12 / 6 = 2 rows.
- `reshape(5, 3)` needs 15 elements, so NumPy raises a `ValueError`. **The element count must match.**
- `hours.reshape(-1, 1)` changes shape `(4,)` into `(4, 1)`, a column.
- `flatten()` always returns a copy, while `ravel()` returns a view when it can.

## 8. Copy vs View

- A **view** is a new array object that **shares the same data** with the original. Changing one changes the other.
- A **copy** has its **own separate data**. Changing one does not affect the other.

| Operation | Result |
|---|---|
| Basic slicing `a[1:4]` | **View** |
| `reshape()`, `ravel()`, `.T` | Usually a **view** |
| `a.copy()`, `flatten()` | **Copy** |
| Fancy indexing `a[[0, 2]]` and boolean indexing `a[a > 5]` | **Copy** |
| `b = a` (just assignment) | Not even a new array, both names point to the same array |

**Analogy:** A view is like a shared Google Sheet link (everyone sees and edits the same data). A copy is like downloading your own Excel file.

**Why it matters:** Views save memory and time, especially for big data. But accidentally editing a view silently changes your original dataset, which is a classic bug.

**Check:** `np.shares_memory(a, b)` or `b.base is a`.

In [9]:
a = np.array([1, 2, 3, 4, 5])

view = a[1:4]            # slicing -> view
view[0] = 99
print("After changing the view, original a:", a)

b = np.array([1, 2, 3, 4, 5])
copy = b[1:4].copy()     # explicit copy
copy[0] = 99
print("After changing the copy, original b:", b)

# Shares memory?
print("\nview shares memory with a :", np.shares_memory(view, a))
print("copy shares memory with b :", np.shares_memory(copy, b))

# Fancy indexing returns a copy
c = np.array([10, 20, 30, 40])
fancy = c[[0, 2]]
fancy[0] = -1
print("\nOriginal c after changing fancy-indexed array:", c)

# Plain assignment is NOT a copy
d = np.array([1, 2, 3])
e = d
e[0] = 100
print("d after changing e:", d)

After changing the view, original a: [ 1 99  3  4  5]
After changing the copy, original b: [1 2 3 4 5]

view shares memory with a : True
copy shares memory with b : False

Original c after changing fancy-indexed array: [10 20 30 40]
d after changing e: [100   2   3]


**Output Explanation:**
- Changing the **view** changed the original array `a` (index 1 became 99). Changing the **copy** left `b` untouched.
- Fancy indexing returns a copy, so `c` did not change.
- `e = d` is only a second name for the same array, so editing `e` edits `d`.

**Rule:** If you will modify a slice and want to keep the original safe, use `.copy()`.

## 9. Broadcasting

**Broadcasting** lets NumPy do math on arrays of **different shapes** by automatically stretching the smaller array to match the bigger one, **without actually copying data**.

**Rules (compare shapes from the right side):**
1. Two dimensions are compatible if they are **equal**, or one of them is **1**.
2. A missing dimension is treated as 1.
3. If the rule fails, NumPy raises a `ValueError`.

| Shapes | Result shape | Works? |
|---|---|---|
| (3, 3) and (3,) | (3, 3) | Yes |
| (3, 1) and (1, 3) | (3, 3) | Yes |
| (3, 4) and (3,) | - | No (4 vs 3) |
| (3, 4) and (4,) | (3, 4) | Yes |

**Analogy:** A teacher adds 5 grace marks to every student. She writes "+5" once, and it applies to the whole class list. She does not write 5 against each name.

**Business example:** Prices of 3 products across 4 stores are in a 3 x 4 table, and tax rates per store are in an array of 4. `prices * (1 + tax)` applies the right tax to each store (column) in one line.

**AI/ML example:** **Standardization** `(X - mean) / std`. X has shape (rows, features), while mean and std have shape (features,). Broadcasting subtracts each column's mean from that whole column. Adding a **bias** vector to a layer's output is also broadcasting.

In [10]:
# Scalar broadcasting
marks = np.array([70, 80, 90])
print("marks + 5:", marks + 5)

# 2D + 1D
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row = np.array([10, 20, 30])
print("\nm + row:\n", m + row)

# Column (3,1) + row (1,3) -> (3, 3) grid
col = np.array([[1], [2], [3]])
row2 = np.array([[10, 20, 30]])
print("\ncol + row2 shapes:", col.shape, row2.shape, "->", (col + row2).shape)
print(col + row2)

# AI/ML: standardize each feature column
scores = np.array([[70, 80, 90],
                   [60, 75, 85],
                   [88, 92, 95]], dtype=float)
col_mean = scores.mean(axis=0)
col_std = scores.std(axis=0)
standardized = (scores - col_mean) / col_std
print("\nColumn means          :", col_mean.round(2))
print("Standardized means    :", standardized.mean(axis=0).round(2))
print("Standardized std      :", standardized.std(axis=0).round(2))

# Incompatible shapes
try:
    np.ones((3, 4)) + np.ones(3)
except ValueError as e:
    print("\nError:", e)

marks + 5: [75 85 95]

m + row:
 [[11 22 33]
 [14 25 36]
 [17 28 39]]

col + row2 shapes: (3, 1) (1, 3) -> (3, 3)
[[11 21 31]
 [12 22 32]
 [13 23 33]]

Column means          : [72.67 82.33 90.  ]
Standardized means    : [-0.  0.  0.]
Standardized std      : [1. 1. 1.]

Error: operands could not be broadcast together with shapes (3,4) (3,) 


**Output Explanation:**
- `marks + 5` stretches the single number 5 to every element.
- `m + row` adds `[10, 20, 30]` to **every row** of `m`.
- A `(3, 1)` column plus a `(1, 3)` row stretches both and gives a full `(3, 3)` grid. This is how multiplication tables are made.
- In the standardization example, `scores - col_mean` subtracts each column's own mean. After standardizing, each column has mean about 0 and standard deviation 1. **No loops were needed.**
- `(3, 4) + (3,)` fails because 4 and 3 are not equal and neither is 1.

## 10. Array Operations

NumPy operations are **element-wise** by default: the operation is applied to each pair of elements at the same position.

| Operation | Meaning |
|---|---|
| `a + b`, `a - b`, `a * b`, `a / b` | Element-wise arithmetic |
| `a ** 2` | Square each element |
| `a > 5` | Element-wise comparison, gives a Boolean array |
| `a @ b` or `np.dot(a, b)` | Matrix multiplication (**not** element-wise, see Notebook 2) |
| `np.where(cond, x, y)` | If-else for the whole array |
| `np.concatenate`, `np.vstack`, `np.hstack` | Joining arrays |

**Important difference from lists:** `[1, 2] * 2` gives `[1, 2, 1, 2]` (repeats), but `np.array([1, 2]) * 2` gives `[2, 4]` (multiplies).

**Business example:** `revenue = price * quantity` gives revenue for all products at once, and `np.where(sales > target, "Hit", "Miss")` labels every salesperson.

**AI/ML example:** Calculating predictions `y_pred = X * w + b` and the error `(y_true - y_pred) ** 2` for the entire dataset in one go.

In [11]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print("a + b :", a + b)
print("a * b :", a * b)
print("b / a :", b / a)
print("a ** 2:", a ** 2)
print("a > 2 :", a > 2)

# List vs array
print("\nList [1, 2] * 2      :", [1, 2] * 2)
print("Array np.array([1, 2]) * 2:", np.array([1, 2]) * 2)

# Business: revenue and labels
price = np.array([100, 250, 80])
qty = np.array([5, 2, 10])
print("\nRevenue:", price * qty)

sales = np.array([120, 80, 150, 95])
print("Labels :", np.where(sales >= 100, "Hit", "Miss"))

# Joining arrays
print("\nconcatenate:", np.concatenate([a, b]))
print("vstack:\n", np.vstack([a, b]))
print("hstack:", np.hstack([a, b]))

# ML style: squared error for all samples at once
y_true = np.array([3.0, 5.0, 7.0])
y_pred = np.array([2.5, 5.5, 8.0])
print("\nSquared errors:", (y_true - y_pred) ** 2)
print("MSE           :", ((y_true - y_pred) ** 2).mean())

a + b : [11 22 33 44]
a * b : [ 10  40  90 160]
b / a : [10. 10. 10. 10.]
a ** 2: [ 1  4  9 16]
a > 2 : [False False  True  True]

List [1, 2] * 2      : [1, 2, 1, 2]
Array np.array([1, 2]) * 2: [2 4]

Revenue: [500 500 800]
Labels : ['Hit' 'Miss' 'Hit' 'Miss']

concatenate: [ 1  2  3  4 10 20 30 40]
vstack:
 [[ 1  2  3  4]
 [10 20 30 40]]
hstack: [ 1  2  3  4 10 20 30 40]

Squared errors: [0.25 0.25 1.  ]
MSE           : 0.5


**Output Explanation:**
- All arithmetic acts position by position: `a + b` is `[11, 22, 33, 44]`.
- `a > 2` gives `[False, False, True, True]`, which can be used as a mask.
- A list repeated with `*`, but an array multiplies each element.
- `np.where` works as a vectorized if-else.
- The squared errors are `[0.25, 0.25, 1.0]`, so the mean squared error is **0.5**. This is the exact formula of MSE, written without any loop.

## 11. Universal Functions (ufuncs)

A **ufunc** is a NumPy function that works **element-wise on whole arrays** at C speed. We have already used some without naming them (`+`, `*`, `>` are ufuncs too).

| Type | Examples |
|---|---|
| Math | `np.add`, `np.subtract`, `np.multiply`, `np.divide`, `np.power`, `np.mod` |
| Exponent and log | `np.exp`, `np.log`, `np.log10`, `np.sqrt` |
| Trigonometry | `np.sin`, `np.cos` |
| Rounding | `np.round`, `np.floor`, `np.ceil`, `np.abs` |
| Comparison | `np.maximum`, `np.minimum`, `np.greater` |
| Special methods | `.reduce()` (collapse to one value), `.accumulate()` (running result) |

**Business example:** `np.log1p(income)` reduces the effect of very high incomes, `np.ceil(weight / 10)` calculates the number of boxes needed for each order.

**AI/ML example:**
- **Sigmoid** activation `1 / (1 + np.exp(-x))` uses `np.exp`.
- **ReLU** activation is `np.maximum(0, x)`.
- **Log transform** (`np.log1p`) of skewed features (Sprint 2).
- **Euclidean distance** uses `np.sqrt` and `**2`.

In [12]:
x = np.array([-2.0, -1.0, 0.0, 1.0, 2.0])

print("abs      :", np.abs(x))
print("sqrt(|x|):", np.sqrt(np.abs(x)).round(2))
print("exp      :", np.exp(x).round(3))
print("round    :", np.round(np.array([1.26, 2.5, 3.14159]), 1))
print("ceil     :", np.ceil(np.array([1.2, 2.7, 3.0])))
print("floor    :", np.floor(np.array([1.2, 2.7, 3.0])))

# Activation functions
sigmoid = 1 / (1 + np.exp(-x))
relu = np.maximum(0, x)
print("\nsigmoid:", sigmoid.round(3))
print("relu   :", relu)

# Log transform of skewed values
income = np.array([20000, 35000, 50000, 2_000_000])
print("\nlog1p(income):", np.log1p(income).round(2))

# reduce and accumulate
nums = np.array([1, 2, 3, 4, 5])
print("\nnp.add.reduce    :", np.add.reduce(nums))
print("np.add.accumulate:", np.add.accumulate(nums))

# Euclidean distance between two points
p1, p2 = np.array([1, 2]), np.array([4, 6])
print("Distance:", np.sqrt(np.sum((p1 - p2) ** 2)))

# out= saves memory by writing the result into an existing array
result = np.empty(5)
np.multiply(x, 2, out=result)
print("\nout= result:", result)

abs      : [2. 1. 0. 1. 2.]
sqrt(|x|): [1.41 1.   0.   1.   1.41]
exp      : [0.135 0.368 1.    2.718 7.389]
round    : [1.3 2.5 3.1]
ceil     : [2. 3. 3.]
floor    : [1. 2. 3.]

sigmoid: [0.119 0.269 0.5   0.731 0.881]
relu   : [0. 0. 0. 1. 2.]

log1p(income): [ 9.9  10.46 10.82 14.51]

np.add.reduce    : 15
np.add.accumulate: [ 1  3  6 10 15]
Distance: 5.0

out= result: [-4. -2.  0.  2.  4.]


**Output Explanation:**
- Each function is applied to **every element**, so no loop is needed.
- Sigmoid squeezes any number into the range 0 to 1 (`sigmoid(0)` is 0.5). ReLU turns negative numbers into 0.
- `np.log1p` shrinks the huge income (20 lakh) so that it does not dominate the others.
- `np.add.reduce` gives the total (15), `np.add.accumulate` gives the running total `[1, 3, 6, 10, 15]`.
- The distance between (1, 2) and (4, 6) is sqrt(9 + 16) = **5.0**.

## Best Practices

- Use **vectorized operations** instead of Python loops.
- Choose the **smallest suitable dtype** (`float32`, `int32`) when memory matters.
- Use `.copy()` when you plan to change a slice and keep the original.
- Check `shape` and `dtype` often, most bugs are shape or type bugs.
- Use `axis` explicitly (axis=0 is down the rows, axis=1 is across the columns).
- Prefer `reshape(-1, n)` over hard-coded sizes.
- Create arrays directly with `zeros`, `arange`, `linspace`, not by appending to a list in a loop.

## Common Mistakes

| Mistake | Problem | Fix |
|---|---|---|
| Treating `b = a` as a copy | Changing `b` changes `a` | Use `a.copy()` |
| Forgetting that a slice is a view | Original data silently changes | Use `.copy()` |
| Mixing strings and numbers | Whole array becomes text | Keep arrays numeric |
| Reshape with wrong element count | `ValueError` | Make the product of the shape equal `size` |
| Using `*` for matrix multiplication | Element-wise result | Use `@` or `np.dot` |
| Expecting `arange` to include stop | Last value missing | Remember stop is excluded |
| Broadcasting wrong shapes | `ValueError` | Compare shapes from the right |
| Using Python `sum`/loops on big arrays | Very slow | Use `np.sum` and vectorized code |

## Advantages
- Very fast and memory-efficient, compared with Python lists
- Short, readable code (no loops) for math on whole datasets
- Powerful indexing, slicing and broadcasting
- Foundation of Pandas, scikit-learn, TensorFlow and PyTorch

## Limitations
- All elements must be of **one type** (not good for mixed tables, that is Pandas)
- Size is **fixed** after creation (appending creates a new array)
- No column names or labels, only positions
- No built-in handling for missing data (`NaN` only for floats)
- Runs on the CPU, large deep learning jobs need GPU libraries
- Whole array must fit in memory